var navBoxData = {
	"name":"测试模板",
	"address":"深圳",
	"time":1513785600000,
	"eventBigType":"事故灾难",
	"eventDetailType":"危险化学品事故",
	"eventCategory":"较大事故(Ⅲ级)",
	"orgList":[
		"组织单位1",
		"组织单位2",
		"组织单位三"
	],
	"stageScenes":[
		{
			"level":1,
			"name":"场景概述",
			"index":0,
			"desc":"场景概述",
			"rule":"演练原则",
			"targets":[
				"目标1",
				"目标2"
			],
			"explain":"场景说明",
			"imgts":[
				{
					"url":"/5/9/0d4a7251-f6bc-4f43-a38a-68c4c7288588.jpeg",
					"desc":"阿斯达四大萨达撒多撒多"
				}
			]
		},
		{
			"level":1,
			"name":"a1",
			"index":1,
			"tasks":[
				{
					"name":"adasdsad",
					"groups":"asdasdasd"
				}
			],
			"explain":"",
			"imgts":[
				{
					"url":"/5/b/01c2b24b-21ef-431f-a780-cfc04ce1be9f.jpeg",
					"desc":"dasdasddsa "
				}
			]
		},
		{
			"level":2,
			"name":"a01",
			"index":2,
			"tasks":[
				{
					"name":"adasdasdsadsadasdasdsa",
					"groups":"asdsaddsa"
				}
			],
			"explain":"",
			"imgts":[
				{
					"url":"/f/0/32e9aaf0-b043-404d-ae0f-18780c71b658.png",
					"desc":"asdasdasdsadsad"
				}
			]
		},
		{
			"level":2,
			"name":"a11",
			"index":3,
			"tasks":[
				{
					"name":"sadasdsad",
					"groups":"dasdasdsad"
				}
			],
			"explain":"asdasdsad",
			"imgts":[
				{
					"url":"/5/b/d69a09bd-9d53-4612-8894-724c31914fc3.jpeg",
					"desc":"asdasdasdasd"
				}
			]
		},
		{
			"level":3,
			"name":"a111",
			"index":4,
			"tasks":[
				{
					"name":"adsasdasdsada",
					"groups":"asdasdasdasda"
				}
			],
			"explain":"asdasdasdsa",
			"imgts":[
				{
					"url":"/5/b/a8fec383-6c0f-4e6a-bf90-b014ed632faf.jpeg",
					"desc":"dasdsadsads"
				}
			]
		},
		{
			"level":1,
			"name":"b1",
			"index":5,
			"tasks":[
				{
					"name":"asdasdsad",
					"groups":"asdasdasdad"
				}
			],
			"explain":"asdasdsad",
			"imgts":[
				{
					"url":"/f/0/43fd3dcc-5f8c-4009-a507-eead6d2766ce.png",
					"desc":"asdasdsadsad"
				}
			]
		},
		{
			"level":1,
			"name":"总结评估",
			"index":6,
			"abilities":[
				{
					"name":"原因清查",
					"url":"/5/9/1f5db879-4aa2-433a-ade0-750cea9cb69b.jpeg",
					"desc":"阿斯达四大萨达多",
					"assess":"阿斯达四大萨达大所多"
				},
				{
					"name":"应急响应",
					"url":"/c/3/9e2e797f-b317-428c-9ef3-7a038b6099d1.png",
					"desc":"阿斯达四大萨达",
					"assess":"阿萨德撒多撒多"
				},
				{
					"name":"应急响应",
					"url":"/5/9/b35ca507-eb25-40a2-be90-e9473a791b9e.jpeg",
					"desc":"阿斯达四大萨达",
					"assess":"阿斯达四大萨达"
				}
			]
		}
	],
	"id":868792040
}


var data_data = [
	{
		"childs":[],
		"stageScene":{
			"desc":"场景概述",
			"explain":"场景说明",
			"imgts":[
				{
					"desc":"阿斯达四大萨达撒多撒多",
					"url":"/5/9/0d4a7251-f6bc-4f43-a38a-68c4c7288588.jpeg"
				}
			],
			"index":0,
			"level":1,
			"name":"场景概述",
			"rule":"演练原则",
			"targets":["目标1","目标2"]
		}
	},
	{
		"childs":[
			{
				"explain":"",
				"imgts":[
					{
						"desc":"asdasdasdsadsad",
						"url":"/f/0/32e9aaf0-b043-404d-ae0f-18780c71b658.png"
					}
				],
				"index":2,
				"level":2,
				"name":"a01",
				"tasks":[
					{
						"groups":"asdsaddsa",
						"name":"adasdasdsadsadasdasdsa"
					}
				]
			},
			{
				"explain":"asdasdsad",
				"imgts":[
					{
						"desc":"asdasdasdasd",
						"url":"/5/b/d69a09bd-9d53-4612-8894-724c31914fc3.jpeg"
					}
				],
				"index":3,
				"level":2,
				"name":"a11",
				"tasks":[
					{
						"groups":"dasdasdsad",
						"name":"sadasdsad"
					}
				]
			},
			{
				"explain":"asdasdasdsa",
				"imgts":[
					{
						"desc":"dasdsadsads",
						"url":"/5/b/a8fec383-6c0f-4e6a-bf90-b014ed632faf.jpeg"
					}
				],
				"index":4,
				"level":3,
				"name":"a111",
				"tasks":[
					{
						"groups":"asdasdasdasda",
						"name":"adsasdasdsada"
					}
				]
			}
		],
		"stageScene":{
			"explain":"",
			"imgts":[
				{
					"desc":"dasdasddsa ",
					"url":"/5/b/01c2b24b-21ef-431f-a780-cfc04ce1be9f.jpeg"
				}
			],
			"index":1,
			"level":1,
			"name":"a1",
			"tasks":[
				{
					"groups":"asdasdasd",
					"name":"adasdsad"
				}
			]
		}
	},
	{
		"childs":[],
		"stageScene":{
			"explain":"asdasdsad",
			"imgts":[
				{
					"desc":"asdasdsadsad",
					"url":"/f/0/43fd3dcc-5f8c-4009-a507-eead6d2766ce.png"
				}
			],
			"index":5,
			"level":1,
			"name":"b1",
			"tasks":[
				{
					"groups":"asdasdasdad",
					"name":"asdasdsad"
				}
			]
		}
	},
	{
		"childs":[],
		"stageScene":{
			"abilities":[
				{
					"assess":"阿斯达四大萨达大所多",
					"desc":"阿斯达四大萨达多",
					"name":"原因清查",
					"url":"/5/9/1f5db879-4aa2-433a-ade0-750cea9cb69b.jpeg"
				},
				{
					"assess":"阿萨德撒多撒多",
					"desc":"阿斯达四大萨达",
					"name":"应急响应",
					"url":"/c/3/9e2e797f-b317-428c-9ef3-7a038b6099d1.png"
				},
				{
					"assess":"阿斯达四大萨达",
					"desc":"阿斯达四大萨达",
					"name":"应急响应",
					"url":"/5/9/b35ca507-eb25-40a2-be90-e9473a791b9e.jpeg"
				}
			],
			"index":6,
			"level":1,
			"name":"总结评估"
		}
	}
]

